### PR TITLE
Made a discord weather bot

### PR DESCRIPTION
**Pull request by wasimreja**
Made a discord weather bot that displays weather information of a given city.

#30 

preview

### CODE REVIEW

**Comment by neelshah2409** [comment]
Great work 🎊

**Comment by wasimreja** [comment]
@neelshah2409 could you assign the label as medium, moderate label won't count as points in JWoC.

**Comment by wasimreja** [comment]
@neelshah2409 could you assign this label as medium? moderate label won't count points in JWoC.

**Comment by wasimreja** [comment]
@neelshah2409 could you assign the label as medium? moderate label won't count as points in JWoC.

**Pull request merged**
