### PR TITLE
added new features to the covid telegram bot

### PR DESCRIPTION
**Pull request by r3yc0n1c**
Resolved issues: #9, #14

### Summary
* Added the **search by country** feature
* Added docs

***

```
/stats [country]
```
image

### CODE REVIEW

**Comment by neelshah2409** [comment]
> Resolved issues: #9, #14
> 
> ### Summary
> * Added the **search by country** feature
> * Added docs
> 
> ```
> /stats [country]
> ```
> 
> image

Also you can add state wise and area wise if possible.

**Comment by r3yc0n1c** [comment]
Sorry for the late update but I couldn't find the state or areawise data from this API. Can you merge this PR, please? I'll try to look for other APIs and update this feature if I find one. Thank you in advance.

**Comment by neelshah2409** [comment]
> r3yc0n1c

Okay !!

**Comment by r3yc0n1c** [comment]
thanks a lot... but can you add the `medium` level please as it was under that category?

**Pull request merged**
