### PR TITLE
voice commanded email bot

### PR DESCRIPTION
**Pull request by Shubham-Patel07**
This is the code for the voice recognition automation bot. we can send emails with your voice commands without typing anything which is very helpful in sending multiple emails in a very short duration

### CODE REVIEW

**Comment by neelshah2409** [comment]
Awesome work just attache the ss here of you output.

**Comment by Shubham-Patel07** [comment]
image

**Comment by neelshah2409** [comment]
Awesome work 🎊

**Comment by Shubham-Patel07** [comment]
@neelshah2409 are you from ITNU?

**Comment by Shubham-Patel07** [comment]
@neelshah2409 are you from ITNU?

**Comment by Shubham-Patel07** [comment]
> Awesome work 🎊

Thanks 😊

**Pull request merged**
