### PR TITLE
email module

### PR DESCRIPTION
**Pull request by natiwb**
This adds an email and text module, it does not automate the process as of yet however it does carry out the email and text notifications in a secure way.

### CODE REVIEW

**Comment by neelshah2409** [comment]
Okay great just attach your output ss here .

**Comment by natiwb** [comment]
There is no output unless you want to see the test email I sent from it?

**Comment by neelshah2409** [comment]
> There is no output unless you want to see the test email I sent from it?

Yes !!

**Comment by neelshah2409** [comment]
Awesome work 👏

**Comment by natiwb** [comment]
> 

image
Thanks!

**Pull request merged**
