### PR TITLE
Addition of emailSending

### PR DESCRIPTION
**Pull request by Arghya-Banerjee**
I made this first-time program to send emails to bulk my typing their email address each time the loop executes. If you want I can work on this by reading you a CSV file containing all the email addresses of the receivers.

### CODE REVIEW

**Comment by neelshah2409** [comment]
> I made this first-time program to send emails to bulk my typing their email address each time the loop executes. If you want I can work on this by reading you a CSV file containing all the email addresses of the receivers.

Yes please do it with csv.

**Comment by neelshah2409** [comment]
@Arghya-Banerjee ,what happened, why you closed the issue??

**Comment by Arghya-Banerjee** [comment]
Was having a personal prob related to the code in the pr thus I closed it. But don't worry I am working on giving the script to send mail reading CSV.

**Comment by Arghya-Banerjee** [comment]
I will open a new one when done including both the scripts

**Pull request closed without merging**
